### ISSUE TITLE
Implement "Atbash" function and write new test

### ISSUE THREAD

**Issue by ifedyukin** [ifedyukin/hacktoberfest-js-utils#27]

**Comment by bakoushin** [comment]
## Task description
Implement Atbash cipher/deciper for Latin alphabet.
Atbash is an old Hebrew substitution cipher, used in Bible. [Wikipedia](https://en.wikipedia.org/wiki/Atbash)

In the Atbash cipher, alphabet is mapped to its reverse, so the first letter becomes the last letter, the second letter becomes the second to last letter, and so on.

Atbash mapping for Latin alphabet:
```
A|B|C|D|E|F|G|H|I|J|K|L|M
Z|Y|X|W|V|U|T|S|R|Q|P|O|N
```
